defaults: &defaults
  accept_jobs_domain_email: pingyoupingzhu@163.com
  system_mailer_addressee: pingyoupingzhu@163.com
  tld: dev
  redis:
    host: localhost
    port: 6379
    redis: redis://localhost:6379
  search: http://localhost:9200

development:
  <<: *defaults

devprod:
  <<: *defaults

qa:
  <<: *defaults
  tld: qa

production:
  <<: *defaults
  tld: com
  redis:
    host: localhost
    port: 6379
    redis: redis://localhost:6379
  search: http://localhost:9200

test:
  <<: *defaults
