defaults: &defaults
  user:
    user0:
      username: wushanshan
      password: wushanshan
      password_confirmation: wushanshan
      category: student

    user1:
      username: xuegongchu
      password: xuegongchu
      password_confirmation: xuegongchu
      category: xuegongchu

    admin:
      username: admin
      password: admin
      password_confirmation: admin
      category: :admin



development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
