defaults: &defaults
  user:
    user0:
      username: zhangcaiyan
      password: 123456
      password_confirmation: 123456
      category: student

    user1:
      username: xuegongchu
      password: 123456
      password_confirmation: 123456
      category: xuegongchu

    admin:
      username: admin
      password: 123456
      password_confirmation: 123456
      category: :admin



development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
